.TH UCRYPT 7 2016-12-24 Linux "Upamanyu Software"
.SH NAME
ucrypt \- toy cryptography utilities
.SH SYNOPSIS
.B ucrypt
\fIinput_file\fR
[\fB\-o\fR \fIoutput_file\fR]
.SH DESCRIPTION
.B ucrypt
provides several utilities for toy/puzzle cryptography. At present, the only
available functionality is the Vigenere cipher.
.SH OPTIONS
.TP
.BR \-o " " \fIoutput_file\fR
outputs the ciphertext to output_file instead of stdout
